# Generated by Django 4.1.13 on 2025-11-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/exercises', verbose_name='Photo_Exercise')),
                ('repetitions', models.IntegerField(default=0)),
                ('times', models.IntegerField(default=0)),
                ('video_link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/programs', verbose_name='Photo_Program')),
                ('description', models.TextField(max_length=250, null=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration', models.CharField(choices=[('short', 'Up to 4 weeks'), ('medium', '4 to 8 weeks'), ('long', 'More than 8 weeks')], default='medium', max_length=20)),
                ('goal', models.CharField(choices=[('strength', 'Build Strength'), ('endurance', 'Improve Endurance'), ('weight_loss', 'Weight Loss'), ('mobility', 'Mobility & Flexibility')], default='strength', max_length=20)),
                ('exercises', models.ManyToManyField(blank=True, related_name='exercises', to='fitness.exercises', verbose_name='Exercises')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('programs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='fitness.programs', verbose_name='Programs')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercises', models.ManyToManyField(blank=True, related_name='day_exercises', to='fitness.exercises')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_train', to='fitness.programs')),
            ],
        ),
    ]
