# Generated by Django 4.1.13 on 2024-05-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='fitness.exercises', verbose_name='Exercises'),
        ),
    ]
