# Generated by Django 4.1.13 on 2024-05-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exercises', models.ManyToManyField(blank=True, related_name='day_exercises', to='fitness.exercises')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_train', to='fitness.programs')),
            ],
        ),
    ]
