# Generated by Django 4.1.13 on 2024-05-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_programs_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/exercises', verbose_name='Photo_Exercise'),
        ),
        migrations.AddField(
            model_name='programs',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/programs', verbose_name='Photo_Program'),
        ),
    ]
