# Generated by Django 4.1.13 on 2024-05-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_exercises_photo_programs_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
