# Generated by Django 4.1.13 on 2024-05-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_programs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
