# Generated by Django 4.1.13 on 2024-05-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_alter_programs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercises',
            name='times',
            field=models.IntegerField(default=0),
        ),
    ]
