# Generated by Django 4.1.13 on 2024-05-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_exercises_repetitions_exercises_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='video_link',
            field=models.URLField(null=True),
        ),
    ]
