# Generated by Django 4.1.13 on 2025-11-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1500)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/foodplans', verbose_name='Photo_Foodplan')),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('maintenance', 'Maintenance'), ('weight_gain', 'Weight Gain'), ('muscle_gain', 'Muscle Gain')], default='maintenance', max_length=20)),
                ('diet_type', models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('keto', 'Keto'), ('balanced', 'Balanced'), ('low_carb', 'Low Carb')], default='balanced', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=1500)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/dish_photos', verbose_name='Photo_Dish')),
                ('calories', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=1500)),
                ('proteins', models.IntegerField(default=0)),
                ('fats', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Supplement_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Supplements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('content', models.CharField(blank=True, max_length=1500)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/supplement_photos', verbose_name='Photo_Supp')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supp_cat', to='lifestyle.supplement_cat', verbose_name='Supplement_category')),
            ],
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('foodplans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='food_plans', to='lifestyle.foodplans', verbose_name='FoodPlans')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodplan', to='lifestyle.foodplans')),
                ('meals', models.ManyToManyField(blank=True, related_name='day_meals', to='lifestyle.meals')),
            ],
        ),
    ]
