# Generated by Django 4.1.13 on 2024-05-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodplans',
            name='meals',
        ),
    ]
