# Generated by Django 4.1.13 on 2024-05-08 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0003_foodplans_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='food_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodplan', to='lifestyle.foodplans'),
        ),
    ]
