# Generated by Django 4.1.13 on 2024-05-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0004_alter_day_food_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/dish_photos', verbose_name='Фото'),
        ),
    ]
