# Generated by Django 4.1.13 on 2024-05-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0005_meals_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplans',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/foodplans', verbose_name='Photo_Foodplan'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/dish_photos', verbose_name='Photo_Dish'),
        ),
    ]
