# Generated by Django 4.1.13 on 2024-05-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0006_foodplans_photo_alter_meals_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Supplements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/supplement_photos', verbose_name='Photo_Supp')),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wuman', to='lifestyle.supplement_cat', verbose_name='Supplement_category')),
            ],
        ),
    ]
