# Generated by Django 4.1.13 on 2024-05-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0007_supplement_cat_supplements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplements',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supp_cat', to='lifestyle.supplement_cat', verbose_name='Supplement_category'),
        ),
    ]
