# Generated by Django 4.1.13 on 2024-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0008_alter_supplements_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodplans',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
