# Generated by Django 4.1.13 on 2024-05-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0009_alter_foodplans_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodplans',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
