# Generated by Django 4.1.13 on 2024-05-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0010_alter_foodplans_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='meals',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
