# Generated by Django 4.1.13 on 2024-05-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0015_alter_meals_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplements',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='content',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
