# Generated by Django 4.1.13 on 2024-05-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0016_supplements_description_alter_supplements_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meals',
            name='fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meals',
            name='proteins',
            field=models.IntegerField(default=0),
        ),
    ]
