# Generated by Django 4.1.13 on 2025-06-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0017_meals_carbs_meals_fats_meals_proteins'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplans',
            name='diet_type',
            field=models.CharField(choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('keto', 'Keto'), ('balanced', 'Balanced'), ('low_carb', 'Low Carb')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='foodplans',
            name='goal',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('maintenance', 'Maintenance'), ('weight_gain', 'Weight Gain'), ('muscle_gain', 'Muscle Gain')], default='maintenance', max_length=20),
        ),
    ]
