# Generated by Django 4.1.13 on 2025-05-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_exercises_video_link'),
        ('lifestyle', '0017_meals_carbs_meals_fats_meals_proteins'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_fitness_program',
            field=models.ForeignKey(blank=True, limit_choices_to={'program_type': 'fitness'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_fitness', to='fitness.programs', verbose_name='Fitness-Program'),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_nutrition_program',
            field=models.ForeignKey(blank=True, limit_choices_to={'program_type': 'nutrition'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_nutrition', to='lifestyle.foodplans', verbose_name='Food Plan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(choices=[(False, 'Man'), (True, 'Woman')], default=0, verbose_name='Стать'),
        ),
    ]
